services:
  api:
    build: .
    container_name: bolsa-api-nest
    command: ["node", "dist/src/main.js"]
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=your-super-secret-jwt-key-here
      - DATABASE_URL=postgresql://user:bolsa2024!@db:5432/bolsa_sim
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: bolsa-db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: bolsa2024!
      POSTGRES_DB: bolsa_sim
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
